services:
  - type: web
    name: image-uploader
    env: node
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /healthz
    startCommand: npm run start
    buildCommand: npm install